name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@v1.2.0
      with:
        rust-version: ${{ matrix.rust }}
        components: rustfmt  # Comma-separated
    - uses: actions/checkout@v1
    - name: fmt check
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
