name: Rust

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    matrix:
        os: [ubuntu-latest]
        rust: [stable, nightly]

    steps:
    - uses: hecrj/setup-rust-action@v1.2.0
      with:
        rust-version: ${{ matrix.rust }}
        components: rustfmt
    - uses: actions/checkout@v1
    - name: fmt check
      run: cargo fmt --all -- --check
    - name: clippy
      run: cargo clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
